// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package route

import (
	"server/api/route"
)

type ControllerV1 struct{}

func NewV1() route.IRouteV1 {
	return &ControllerV1{}
}
