// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package login

import (
	"server/api/login"
)

type ControllerV1 struct{}

func NewV1() login.ILoginV1 {
	return &ControllerV1{}
}
