// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package policy

import (
	"server/api/policy"
)

type ControllerV1 struct{}

func NewV1() policy.IPolicyV1 {
	return &ControllerV1{}
}
