// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalAuthenticatesDao is internal type for wrapping internal DAO implements.
type internalAuthenticatesDao = *internal.AuthenticatesDao

// authenticatesDao is the data access object for table authenticates.
// You can define custom methods on it to extend its functionality as you wish.
type authenticatesDao struct {
	internalAuthenticatesDao
}

var (
	// Authenticates is globally public accessible object for table authenticates operations.
	Authenticates = authenticatesDao{
		internal.NewAuthenticatesDao(),
	}
)

// Fill with you ideas below.
