// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalForwardLimitRulesDao is internal type for wrapping internal DAO implements.
type internalForwardLimitRulesDao = *internal.ForwardLimitRulesDao

// forwardLimitRulesDao is the data access object for table forward_limit_rules.
// You can define custom methods on it to extend its functionality as you wish.
type forwardLimitRulesDao struct {
	internalForwardLimitRulesDao
}

var (
	// ForwardLimitRules is globally public accessible object for table forward_limit_rules operations.
	ForwardLimitRules = forwardLimitRulesDao{
		internal.NewForwardLimitRulesDao(),
	}
)

// Fill with you ideas below.
