// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalForwardRulesDao is internal type for wrapping internal DAO implements.
type internalForwardRulesDao = *internal.ForwardRulesDao

// forwardRulesDao is the data access object for table forward_rules.
// You can define custom methods on it to extend its functionality as you wish.
type forwardRulesDao struct {
	internalForwardRulesDao
}

var (
	// ForwardRules is globally public accessible object for table forward_rules operations.
	ForwardRules = forwardRulesDao{
		internal.NewForwardRulesDao(),
	}
)

// Fill with you ideas below.
