// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalInputLimitRulesDao is internal type for wrapping internal DAO implements.
type internalInputLimitRulesDao = *internal.InputLimitRulesDao

// inputLimitRulesDao is the data access object for table input_limit_rules.
// You can define custom methods on it to extend its functionality as you wish.
type inputLimitRulesDao struct {
	internalInputLimitRulesDao
}

var (
	// InputLimitRules is globally public accessible object for table input_limit_rules operations.
	InputLimitRules = inputLimitRulesDao{
		internal.NewInputLimitRulesDao(),
	}
)

// Fill with you ideas below.
