// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalLogSettingsDao is internal type for wrapping internal DAO implements.
type internalLogSettingsDao = *internal.LogSettingsDao

// logSettingsDao is the data access object for table log_settings.
// You can define custom methods on it to extend its functionality as you wish.
type logSettingsDao struct {
	internalLogSettingsDao
}

var (
	// LogSettings is globally public accessible object for table log_settings operations.
	LogSettings = logSettingsDao{
		internal.NewLogSettingsDao(),
	}
)

// Fill with you ideas below.
