// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalLogShellDao is internal type for wrapping internal DAO implements.
type internalLogShellDao = *internal.LogShellDao

// logShellDao is the data access object for table log_shell.
// You can define custom methods on it to extend its functionality as you wish.
type logShellDao struct {
	internalLogShellDao
}

var (
	// LogShell is globally public accessible object for table log_shell operations.
	LogShell = logShellDao{
		internal.NewLogShellDao(),
	}
)

// Fill with you ideas below.
