// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalOutputRulesDao is internal type for wrapping internal DAO implements.
type internalOutputRulesDao = *internal.OutputRulesDao

// outputRulesDao is the data access object for table output_rules.
// You can define custom methods on it to extend its functionality as you wish.
type outputRulesDao struct {
	internalOutputRulesDao
}

var (
	// OutputRules is globally public accessible object for table output_rules operations.
	OutputRules = outputRulesDao{
		internal.NewOutputRulesDao(),
	}
)

// Fill with you ideas below.
