// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalRuleDao is internal type for wrapping internal DAO implements.
type internalRuleDao = *internal.RuleDao

// ruleDao is the data access object for table rule.
// You can define custom methods on it to extend its functionality as you wish.
type ruleDao struct {
	internalRuleDao
}

var (
	// Rule is globally public accessible object for table rule operations.
	Rule = ruleDao{
		internal.NewRuleDao(),
	}
)

// Fill with you ideas below.
