// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSnatRulesDao is internal type for wrapping internal DAO implements.
type internalSnatRulesDao = *internal.SnatRulesDao

// snatRulesDao is the data access object for table snat_rules.
// You can define custom methods on it to extend its functionality as you wish.
type snatRulesDao struct {
	internalSnatRulesDao
}

var (
	// SnatRules is globally public accessible object for table snat_rules operations.
	SnatRules = snatRulesDao{
		internal.NewSnatRulesDao(),
	}
)

// Fill with you ideas below.
