// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSqliteSequenceDao is internal type for wrapping internal DAO implements.
type internalSqliteSequenceDao = *internal.SqliteSequenceDao

// sqliteSequenceDao is the data access object for table sqlite_sequence.
// You can define custom methods on it to extend its functionality as you wish.
type sqliteSequenceDao struct {
	internalSqliteSequenceDao
}

var (
	// SqliteSequence is globally public accessible object for table sqlite_sequence operations.
	SqliteSequence = sqliteSequenceDao{
		internal.NewSqliteSequenceDao(),
	}
)

// Fill with you ideas below.
