// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package public

import (
	"server/api/public"
)

type ControllerV1 struct{}

func NewV1() public.IPublicV1 {
	return &ControllerV1{}
}
