// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package audit

import (
	"server/api/audit"
)

type ControllerV1 struct{}

func NewV1() audit.IAuditV1 {
	return &ControllerV1{}
}
